### PR TITLE
Updates for dev tidyselect

### PR DESCRIPTION
**Pull request by hadley**
Since .data is deprecated.

### CODE REVIEW

**Comment by rfiorella** [comment]
Thanks Hadley! 

Is the .data deprecation documented anywhere? (checked the dplyr and rlang NEWS pages, but presumably this is a new change?) - I have a few other codes using .data that I'd like to make sure are updated consistent with this change.

**Comment by hadley** [comment]
It's in the news: https://github.com/r-lib/tidyselect/blob/main/NEWS.md. But I should make it more prominent...

**Comment by rfiorella** [comment]
Ah, thanks - got it! I had been looking at news at tidyselect.r-lib.org and missed the version on GitHub. 
Thanks again!

**Comment by hadley** [comment]
Ooh hmmm, looks like the website isn't updating. Let me look into that.

**Comment by hadley** [comment]
Ooooh, no, we're just in a confusing state (which will be resolved on release) — you need to go to https://tidyselect.r-lib.org/dev/

**Pull request merged**
