### PR TITLE
Min nob

### PR DESCRIPTION
**Pull request by NDurden**
We are testing this new workflow at a couple sites and I realized that I did not adjust the minimum observation number (min_nobs) in the select_daily_reference_data funtion. To be able to adjust min_nobs values, I also added min_nobs parameter into fit_carbon_regression and calibrate_carbon. @rfiorella, please review.

Do you have any thought on a good min_nobs for the new 6min  observation period? I set the initial value at 130 (~60% of total measurement values in 6 mins (~210)). Thanks.

### CODE REVIEW

**Review by rfiorella — APPROVED** [review]

**Review by rfiorella — COMMENTED** [review]
Hi @NDurden - Looks good, could you also open a PR to rc-0.7 branch? I am doing some refactoring there for the next release and want to make sure that this change doesn't disappear when I merge that branch to main. Thanks!

**Comment by NDurden** [comment]
@rfiorella, will you be able to pull this PR to the main branch and make a patch release before releasing rc-0.7?

**Comment by rfiorella** [comment]
@NDurden yes - I can release this as 0.6.3 on CRAN.
I need to figure out why CI is failing (looks like a unit test failure), but will submit to CRAN this week once this is fixed.

**Comment by NDurden** [comment]
@rfiorella, that's great. Please keep me posted. Thanks.

**Comment by rfiorella** [comment]
@NDurden I can't replicate the CI failures locally, seems there's a mismatch between the package and the documentation. I will merge this onto main and debug from there. You may need to rebase if you want to continue developing in this branch.

**Pull request merged**
